# numpy Basics

In [1]:
import numpy as np

In [2]:
a=np.arange(2,10)

In [3]:
b=np.array([8,7,6,5,4,3,2],dtype="i")
c=a[2:5]
print(c[1])

5


In [4]:
a.shape

(8,)

In [5]:
d=a.reshape(4,2)
d.dtype

dtype('int64')

In [6]:
e=d.astype('int')
e.dtype

dtype('int64')

In [7]:
e=np.concatenate((d,e))

In [8]:
e

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
q=np.array_split(e,3)
q

[array([[2, 3],
        [4, 5],
        [6, 7]]),
 array([[8, 9],
        [2, 3],
        [4, 5]]),
 array([[6, 7],
        [8, 9]])]

In [10]:
np.arange(2,6,dtype='complex')

array([2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [11]:
np.random.randint(200)

153

In [12]:
np.random.randint(200,size=(5,4))

array([[ 25,   0,  39, 100],
       [139, 141, 104, 112],
       [ 18, 127,  58,  30],
       [ 86,  78,  19,  32],
       [ 88, 144, 108, 120]], dtype=int32)

In [15]:
np.random.rand(22)

array([0.73366537, 0.34387027, 0.10451444, 0.10906263, 0.30277859,
       0.26735695, 0.42888177, 0.23604289, 0.07382356, 0.33562535,
       0.04511138, 0.58564326, 0.33518817, 0.59494608, 0.17689076,
       0.2507346 , 0.84388016, 0.07066417, 0.890268  , 0.45964292,
       0.73793783, 0.53254689])